// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/inventory.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for InventorySrv service

func NewInventorySrvEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for InventorySrv service

type InventorySrvService interface {
	Sell(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Confirm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type inventorySrvService struct {
	c    client.Client
	name string
}

func NewInventorySrvService(name string, c client.Client) InventorySrvService {
	return &inventorySrvService{
		c:    c,
		name: name,
	}
}

func (c *inventorySrvService) Sell(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "InventorySrv.Sell", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventorySrvService) Confirm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "InventorySrv.Confirm", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InventorySrv service

type InventorySrvHandler interface {
	Sell(context.Context, *Request, *Response) error
	Confirm(context.Context, *Request, *Response) error
}

func RegisterInventorySrvHandler(s server.Server, hdlr InventorySrvHandler, opts ...server.HandlerOption) error {
	type inventorySrv interface {
		Sell(ctx context.Context, in *Request, out *Response) error
		Confirm(ctx context.Context, in *Request, out *Response) error
	}
	type InventorySrv struct {
		inventorySrv
	}
	h := &inventorySrvHandler{hdlr}
	return s.Handle(s.NewHandler(&InventorySrv{h}, opts...))
}

type inventorySrvHandler struct {
	InventorySrvHandler
}

func (h *inventorySrvHandler) Sell(ctx context.Context, in *Request, out *Response) error {
	return h.InventorySrvHandler.Sell(ctx, in, out)
}

func (h *inventorySrvHandler) Confirm(ctx context.Context, in *Request, out *Response) error {
	return h.InventorySrvHandler.Confirm(ctx, in, out)
}
